sudo: true
os: osx
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-osx.pkg
  global:
    secure: MsXOxUnMPqiuSdYJedrf+G1/GYyN2RZxCEQBXWNkuaYCDM+mM4kQkwDE3P9wZ/S3ZxEaeAVg7kCM0PE2tO2dWaaxvInOJpS5RINyUd7RBAtlhXk6ScjvH3xGiC8OcfyPzAbzxaI6pZr4cmPPnhrOKVa43/ykJfObloIDPL1kc2kokMkYrx3AQ3c4D/kvxktwHy1wHKwTVFMAjzMpw68Ve7Q7T4uq6V8aJqWYmT4XR++6EDe/TB+L8yZKJZMRh9p7q5gYdn4YS1QvQugA/a66ZLNcaHrcCXwln8hUXvXfXMrowl/y7hXZ9cWmt2OcXGyQ238YDpZClHtre0bJmWR1HlaG0QLLCZWWxNaWvu3rF5PHC8o+OBze2EgQyFD5XEDxT5w2xPsNNNwJgt3m5H1t/Of5+x5RtPzs95EtINfT2PTxroYPQ3F3DccONYd4IylZEMhAfIgAK+uK5B0qq6VD8lyc0oU+o87bzVk9z8vCLJ3aix3ioaf+56YCwJgZt8tPeY3M1kbPekfrvJYWfmbi0rm4lhc+p7Bae0iavF0d3qoU4CNSORaRy9vBpPpJxDe+sog0bTrEsEdGjzV5BNaPpRfQ+ESvN5hCnv5jYW52zvyCGvuHUPyLgwojKQik2fRX4Ay/nW0QuqTtEarF0EZTxP71LWCfkRRoBRp/jB98y4k=
before_install:
- openssl aes-256-cbc -k $SERVER_KEY_PASS -in assets/server.key.enc -out assets/server.key
  -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- curl $URL --output sfdx-osx.pkg
- sudo installer -pkg sfdx-osx.pkg -target /
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key
  --username $DEVHUB_USERNAME --setdefaultdevhubusername -a huborg
script:
- sfdx force:org:create -v huborg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human -w 10
- sfdx force:org:delete -u ciorg -p
